<?php
// module/events/view/events/events/index.phtml:

$title = 'Events';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('add', array('action' => 'add')); ?>">Add new events</a>
</p>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Date</th>
		<th>Time</th>
		<th>Location</th>
	</tr>
	<?php foreach ($events as $event) : ?>
		<tr>
			<td><?php echo $this->escapeHtml($event->title); ?></td>
			<td><?php echo $this->escapeHtml($event->description); ?></td>
			<td><?php echo $this->escapeHtml($event->date); ?></td>
			<td><?php echo $this->escapeHtml($event->time); ?></td>
			<td><?php echo $this->escapeHtml($event->location); ?></td>
		</tr>
	<?php endforeach; ?>
</table>